apiVersion: v1
kind: Service
metadata:
  name: nodejs-prom-example
  namespace: default
spec:
  selector:
    app: nodejs-prom-example
    tier: backend
  ports:
    - protocol: "TCP"
      port: 9091
      targetPort: 9091
      name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-prom-example
  namespace: default
spec:
  selector:
    matchLabels:
      app: nodejs-prom-example
      tier: backend
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodejs-prom-example
        tier: backend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - image: norbertdalecker/nodejs-prom-example:1.0.0
          name: nodejs-prom-example
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
              name: backend
